In [3]:
import tensorflow as tf

# Saving Variables

In [7]:
# The file path to save the data
save_file = './saved_models/model.ckpt'

# Two Tensor Variables: weights and bias
weights = tf.Variable(tf.truncated_normal([2, 3]))
bias = tf.Variable(tf.truncated_normal([3]))

# Class used to save and/or restore Tensor Variables
saver = tf.train.Saver()

with tf.Session() as sess:
    # Initialize all the Variables
    sess.run(tf.initialize_all_variables())

    # Show the values of weights and bias
    print('Weights:')
    print(sess.run(weights))
    print('Bias:')
    print(sess.run(bias))

    # Save the model
    saver.save(sess, save_file)

Instructions for updating:
Use `tf.global_variables_initializer` instead.
Weights:
[[ 0.16853099  0.08581524  0.11992227]
 [-0.93516439  0.9224596   0.05598525]]
Bias:
[-0.15893814 -0.4938699   0.58771175]


# Loading Variables

In [8]:
# Remove the previous weights and bias
tf.reset_default_graph()

# Two Variables: weights and bias
weights = tf.Variable(tf.truncated_normal([2, 3]))
bias = tf.Variable(tf.truncated_normal([3]))

# Class used to save and/or restore Tensor Variables
saver = tf.train.Saver()

with tf.Session() as sess:
    # Load the weights and bias
    saver.restore(sess, save_file)

    # Show the values of weights and bias
    print('Weight:')
    print(sess.run(weights))
    print('Bias:')
    print(sess.run(bias))

INFO:tensorflow:Restoring parameters from ./saved_models/model.ckpt
Weight:
[[-1.05522466 -0.38215616  0.26592359]
 [-0.0307714  -0.60719985 -1.40825927]]
Bias:
[-0.63947207 -0.20365258 -0.92629141]
